### ISSUE TITLE
Add alternate logos for different environments

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#1]
We need new logos for each environment:
1. prod
2. prodbeta
3. dev
4. devbeta
5. local

There just needs to be some visual distinction between them. For example, prod is the regular red, prodbeta is yellow, dev and devbeta are green.

**Comment by andrewgioia** [comment]
@mikegioia Logos added, in commit https://github.com/TeachBoost/ui-kit/commit/219bc973b73d21fc4de99096ff89e54a888b889f

| Environment | color | image prefix |
| --- | --- | --- |
| Prod | red | app-badge-prod |
| Prod Beta | blue | app-badge-prodbeta |
| Dev | teal | app-badge-dev |
| Dev Beta | green | app-badge-devbeta |
| Local | purple | app-badge-local |
