### ISSUE TITLE
Icon Request: some paint / palate icon

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#12]
Is it possible to get an icon like this?
![image](https://user-images.githubusercontent.com/387937/31399637-01b2248a-adbb-11e7-9430-48b538aea758.png)

I don't see any free ones in icomoon.

**Comment by andrewgioia** [comment]
@mikegioia I just pushed up with this palette icon, it's .fa-palette

**Comment by mikegioia** [comment]
Thanks @andrewgioia !

**Comment by mikegioia** [comment]
@andrewgioia Can this be closed?

**Comment by andrewgioia** [comment]
Yes, closing out
