### ISSUE TITLE
Icon Request: fa-clipboard

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#2]
http://fontawesome.io/icon/clipboard/

**Comment by andrewgioia** [comment]
@mikegioia https://github.com/TeachBoost/ui-kit/commit/fc9a06bbdfc869a778c92d90e9f1b064b4d67da8 has the new clipboard icon, can you test this and make sure I did the dist build correctly.

**Comment by mikegioia** [comment]
Yea this is good to go
