### ISSUE TITLE
Icon Request: fa-clipboard-check

### ISSUE THREAD

**Issue by jlappano** [TeachBoost/ui-kit#20]
We need a new icon for summatives; Amy requested https://fontawesome.com/icons/clipboard-check?style=light

**Comment by andrewgioia** [comment]
@jlappano just clarifying as I don't think this has come up yet, do you specifically want the light version of this icon? FA has a few different weights and you linked to the light one.

**Comment by jlappano** [comment]
@andrewgioia Yes I think the light one will work best, it's a similar weight to the other buttons on the reports page https://stage.teachboost.net/reports/2784

**Comment by andrewgioia** [comment]
@jlappano @mikegioia this should be good to go in what I just pushed up

**Comment by mikegioia** [comment]
Thanks @andrewgioia it looks good
