### ISSUE TITLE
Icon Request: "retweet" or some cycle icon

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#21]
For reference: https://fontawesome.com/v4.7.0/icon/retweet

We need this for the form cycle icon on a form profile page.

**Comment by andrewgioia** [comment]
@mikegioia it looks like this is already in there: https://github.com/TeachBoost/ui-kit/blob/master/src/less/icons.less#L133

Can you confirm?

**Comment by mikegioia** [comment]
Yes we do already have it, I'm not sure why it wasn't loading for me the first time.
