### ISSUE TITLE
Icon Request: "Pen Quill" or signature icon

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#23]
We need some sort of icon to be used on buttons to "E-Sign" a document.

Some suggested options include:
![image](https://user-images.githubusercontent.com/387937/84084862-255a8080-a999-11ea-8c03-67a1fe158cf5.png)
![image](https://user-images.githubusercontent.com/387937/84084868-28557100-a999-11ea-9949-41d776b1950b.png)

**Comment by andrewgioia** [comment]
@mikegioia I added this to master

**Comment by mikegioia** [comment]
Nice thank you!
