### ISSUE TITLE
Style Request: Card with text

### ISSUE THREAD

**Issue by taliator** [TeachBoost/ui-kit#4]
The linked elements (e.g., "Heatmap") on http://talia.local/titan/reports/10 are supposed to be cards in Raven, but the ui-kit rules display these a bit wonky with the default card CSS. I see that cards usually are only used for data values. Is it possible to get a card style that looks good with text values?

**Comment by taliator** [comment]
![image](https://cloud.githubusercontent.com/assets/1482924/15861697/299b1936-2c9b-11e6-8a80-407b2b0aa892.png)
This is how they look on Raven...

**Comment by mikegioia** [comment]
I'm gonna dump these into raven's `src/sass/common.sass` for now. That's where I'm putting all ui-kit suggestions anyway.

**Comment by mikegioia** [comment]
We may get around this with an `xs-text` on the <a> inside the card.

**Comment by andrewgioia** [comment]
@mikegioia can I delete this? I don't know if it's still relevant.
