### ISSUE TITLE
Icon Request: fa-sliders

### ISSUE THREAD

**Issue by mikegioia** [TeachBoost/ui-kit#7]
Can you please add '.fa-sliders` to the set?

http://fontawesome.io/icon/sliders/

**Comment by mikegioia** [comment]
@andrewgioia Is there any way you can add this today

**Comment by andrewgioia** [comment]
Added in version 0.0.78 https://github.com/TeachBoost/ui-kit/commit/1ff1ece81b7e84f3f5228fbb10bfdae78439f137
